CREATE TABLE IF NOT EXISTS lesson (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS task (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    lesson_id BIGINT NOT NULL,
                                    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    schema_definition TEXT NOT NULL,
    solution_query TEXT NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES lesson(id)
    );